from myapp.models.Action import Action
from myapp.models.ActionLog import ActionLog
from myapp.models.ActionStaticAccumlated import ActionStaticAccumlated
from myapp.models.ActionStudyLog import ActionStudyLog
from myapp.models.ActionStudyProgress import ActionStudyProgress
from myapp.models.BlogPost import BlogPost
from myapp.models.Category import Category
from myapp.models.Comment import Comment
from myapp.models.CommentPost import CommentPost
from myapp.models.Curriculumn import Curriculumn
from myapp.models.CurriculumnLog import CurriculumnLog
from myapp.models.CurriculumnStaticAccumlate import CurriculumnStaticAccumlate
from myapp.models.CurriculumnStudyLog import CurriculumnStudyLog
from myapp.models.CurriculumnStudyProgress import CurriculumnStudyProgress
from myapp.models.Documents import Documents
from myapp.models.Esay import Esay
from myapp.models.Impression import Impression
from myapp.models.JobTitle import JobTitle
from myapp.models.Material import Material
from myapp.models.MaterialLog import MaterialLog
from myapp.models.MaterialStaticAccumlated import MaterialStaticAccumlated
from myapp.models.MaterialStudyLog import MaterialStudyLog
from myapp.models.MaterialStudyProgress import MaterialStudyProgress
from myapp.models.MaterialType import MaterialType
from myapp.models.Mentor import Mentor
from myapp.models.MentorPost import MentorPost
from myapp.models.ProgressType import ProgressType
from myapp.models.RatingPost import RatingPost
from myapp.models.Social import Social
from myapp.models.SocialProfile import SocialProfile
from myapp.models.Student import Student
from myapp.models.Unit import Unit
from myapp.models.UserChat import UserChat
from myapp.models.UserLogin import UserLogin
from myapp.models.UserProfile import UserProfile
from myapp.models.UserType import UserType
from myapp.models.WorkField import WorkField
from myapp.models.StatisticDetail import StatisticDetail
from myapp.models.StudyLog import StudyLog
from myapp.models.LoanType import LoanType
