db.curriculumnstudyprogress.remove();
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[0],
student : db.student.find()[0],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[0],
student : db.student.find()[1],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[0],
student : db.student.find()[2],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[0],
student : db.student.find()[3],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[0],
student : db.student.find()[4],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});


db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[1],
student : db.student.find()[0],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[1],
student : db.student.find()[1],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[1],
student : db.student.find()[2],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[1],
student : db.student.find()[3],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[1],
student : db.student.find()[4],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});


db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[2],
student : db.student.find()[0],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[2],
student : db.student.find()[1],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[2],
student : db.student.find()[2],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[2],
student : db.student.find()[3],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[2],
student : db.student.find()[4],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});


db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[3],
student : db.student.find()[0],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[3],
student : db.student.find()[1],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[3],
student : db.student.find()[2],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[3],
student : db.student.find()[3],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[0],
student : db.student.find()[4],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});


db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[4],
student : db.student.find()[0],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[4],
student : db.student.find()[1],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[4],
student : db.student.find()[2],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[4],
student : db.student.find()[3],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[4],
student : db.student.find()[4],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});


db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[5],
student : db.student.find()[0],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[5],
student : db.student.find()[1],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[5],
student : db.student.find()[2],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[5],
student : db.student.find()[3],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});
db.curriculumnstudyprogress.insert({
published_date : new Date(),
curriculumn: db.curriculumn.find()[5],
student : db.student.find()[4],
impression : db.user.find()[0],
progressType : db.progresstype.find()[0],
planstartdate  : new Date(),
planenddate  : new Date(),
actualstartdate : new Date(),
actualenddate : new Date(),
lastUpdate : new Date(),
});